"""a lot of changes

Revision ID: 08c2650ba3ad
Revises: c710529d1cf0
Create Date: 2022-05-01 16:11:45.315677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c2650ba3ad'
down_revision = 'c710529d1cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=True)
    op.add_column('events', sa.Column('buttons', sa.PickleType(), nullable=True))
    op.add_column('users', sa.Column('reputation', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('mood', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('karma', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'karma')
    op.drop_column('users', 'mood')
    op.drop_column('users', 'reputation')
    op.drop_column('events', 'buttons')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
